### ISSUE TITLE
Wrong image tag

### ISSUE THREAD

**Issue by danielezer** [odavid/k8s-helm-charts#13]
Hwy @odavid :) 
You have an issue with this commit - 658f74244d870ecb5ff9af57218c71a258029ce3

in values.yaml you have added `v` which causes an issue when trying to install the helm chart:
`Back-off pulling image "odavid/my-bloody-jenkins:v2.176.3-151"`

Notice the extra `v` :)

**Comment by odavid** [comment]
10x, sorry...
