### ISSUE TITLE
defaultK8sCloud.name dosen't work as expected

### ISSUE THREAD

**Issue by hzliangbin** [odavid/k8s-helm-charts#15]
I changed defaultK8sCloud.name to "kubernetes" in values.yaml, but jenkins still configs cloud name as "k8s". 
I checked the config.yaml and the following statement was found :

{{ default .Values.defaultK8sCloud.name "k8s" }}

and the statement is  written as 

{{ .Values.defaultK8sCloud.name | default "k8s"  | quote}} 

more often. 

Do I mistake something? thx

**Comment by odavid** [comment]
@hzliangbin 
You are right! It is indeed a bug.
Thank you!
