### ISSUE TITLE
connection with node/slave ? seed-job?

### ISSUE THREAD

**Issue by grinb** [odavid/k8s-helm-charts#2]
Hi,

Recently I work with you repo in docker-compose and all was ok...

When I switch to kubernetes I succeed to helm install and get the Jenkins URL up...

But I have two main problems:

How I managed the containers nodes for a job?

I cant see that is up in the pod.

Also like was in the compose config in the seed job section (git hub URL....) is missing

Thanks,

Eran

**Comment by odavid** [comment]
Hi Eran,

Thanks for trying out this helm chart!

Basically the `managedConfig` section within the values.yaml is responsible for all the configuration same as the config.yml in the docker-compose example.

By default, A kubernetes cloud is configured with nodes labeled as `generic`, so if you create a pipeline job and use:
```
node('generic'){
   sh 'java -version`
}
```
You should see a node being provisioned.
Same goes for seed jobs and all other configuration elements that [my-bloody-jenkins](https://github.com/odavid/my-bloody-jenkins#configuration-reference) configuration has to offer.

Regards,
Ohad

**Comment by grinb** [comment]
Ok thanks.
My question is now how to implment ci in config that trigger build on every push to master ?

**Comment by odavid** [comment]
@grinb , This is a bit beyond the scope of this helm chart, but as a concept, you should use [job-dsl](https://plugins.jenkins.io/job-dsl) plugin.

An example for creating a github organization folder can be found [here](https://github.com/odavid/my-bloody-jenkins/issues/88#issuecomment-385764987)

This example uses the `job_dsl_scripts` configuration section to run `Job DSL Scriptlets` as part of the configuration 

Hope it helps,
Ohad
