### ISSUE TITLE
Add this helm repo to chartcenter.io

### ISSUE THREAD

**Issue by rimusz** [odavid/k8s-helm-charts#22]
@odavid would you mind to open a PR in https://github.com/jfrog/chartcenter/blob/master/repos.yaml, so your helm repo
is officially part of the chartcenter.io?
chartcenter.io is the new central helm charts repo which even can be used from the helm client :)

**Comment by odavid** [comment]
Hi @rimusz - See https://github.com/jfrog/chartcenter/pull/17

Cheers
