### ISSUE TITLE
managedConfig merging issue

### ISSUE THREAD

**Issue by r-whites** [odavid/k8s-helm-charts#23]
During a release upgrade with custom values, Helm encounters a problem while merging managedConfig as below:

`coalesce.go:160: warning: skipped value for managedConfig: Not a table.`

Helm Info:

`version.BuildInfo{Version:"v3.3.4", GitCommit:"a61ce5633af99708171414353ed49547cf05013d", GitTreeState:"dirty", GoVersion:"go1.15.2"}`

The possible issue is related to the absence of `{}` after managedConfig, causing Helm to treat it as a scalar. 

https://github.com/odavid/k8s-helm-charts/blob/53c3e4bd342d6508f16f9c05d90f90575a8046a5/charts/my-bloody-jenkins/values.yaml#L233

Related issue: https://github.com/helm/helm/issues/8283

**Comment by odavid** [comment]
Hey @r-whites - I've changed the managedConfig default value to be `{}`. 
I never encountered such an issue before, can you confirm it works for you with the new version?

**Comment by r-whites** [comment]
@odavid thank you for the quick reply! I have updated the helm chart repo and it is indeed working normally now.
