### ISSUE TITLE
Helm repo 404

### ISSUE THREAD

**Issue by mikaelhachaturian** [odavid/k8s-helm-charts#28]
hi @odavid 
seems after the latest merge, the helm repo stopped working and it is throwing 404

I tried to look around the repo but i cant find the source of the problem, can you take a look when you can?

thanks

**Comment by mkyc** [comment]
I do not see `gh-pages` branch mentioned [here (in Run chart-releaser)](https://github.com/odavid/k8s-helm-charts/runs/6440460616?check_suite_focus=true#step:5:49) so [website](https://odavid.github.io/k8s-helm-charts) shows `404`.

**Comment by odavid** [comment]
Sorry, missed this :( - it seems the gh-pages branch disappeared...
Will need to investigate it

**Comment by odavid** [comment]
I am sorry for that...
The last release somehow deleted my gh-pages...

I've restored it, but only for latest chart...
Closing this issue, and again sorry
