### ISSUE TITLE
Add this helm repo to hub.helm.sh

### ISSUE THREAD

**Issue by rimusz** [odavid/k8s-helm-charts#7]
Hey, thanks for the awesome “My Bloody Jenkins” !
You should add this chart repo to the new distributed Helm hub https://hub.helm.sh
so everybody can leverage the “My Bloody Jenkins” :)
Process is so easy https://github.com/helm/hub/blob/master/Repositories.md

**Comment by odavid** [comment]
Thank you @rimusz  
I will!
Best,
Ohad

**Comment by odavid** [comment]
@rimusz - Created this PR, https://github.com/helm/hub/pull/44 
Please let me know if it is sufficient.

**Comment by odavid** [comment]
Thank you!
